# YAML 
## Re-doing the S. mutans genome from March 2023 to see if the mashtree results are the same as the anvio results I gave Stephanie before (because Anvi'o updated and doesn't want to run with so many genomes now)

reference_genomes:
  accession_list:
  - "GCF_000339535"
  - "GCF_000340155"
  - "GCF_006386535"
  - "GCF_015670115"
  - "GCF_028325945"
  - "GCF_028326165"
  - "GCF_028326145"
  - "GCF_028326125"
  - "GCF_015668935"
  - "GCF_028326065"
  - "GCF_015556125"
  - "GCF_001069835"
  - "GCF_001068415"
  - "GCF_000339695"
  - "GCF_000339715"
  - "GCF_000339255"
  - "GCF_000339515"
  - "GCF_000339155"
  - "GCF_000339235"
  - "GCF_000340095"
  - "GCF_000339655"
  - "GCF_014842815"
  - "GCF_000339195"
  - "GCF_000339735"
  - "GCF_000339675"
  - "GCF_000339175"
  - "GCF_000339215"
  - "GCF_000339275"
  - "GCF_000340115"
  - "GCF_000339595"
  - "GCF_026782885"
  - "GCF_026782845"
  - "GCF_026782825"
  - "GCF_026782805"
  - "GCF_000339775"
  - "GCF_000339315"
  - "GCF_001703615"
  - "GCF_027683265"
  - "GCF_027658645"
  - "GCF_003466855"
  - "GCF_001625005"
  - "GCF_000339555"
  - "GCF_000522765"
  - "GCF_014621675"
  - "GCF_000522565"
  - "GCF_000522805"
  - "GCF_000522665"
  - "GCF_000522785"
  - "GCF_000522625"
  - "GCF_000522685"
  - "GCF_000522725"
  - "GCF_000522645"
  - "GCF_000522905"
  - "GCF_000522745"
  - "GCF_000522925"
  - "GCF_000522945"
  - "GCF_026782785"
  - "GCF_000522605"
  - "GCF_026782765"
  - "GCF_000522585"
  - "GCF_026782745"
  - "GCF_000522865"
  - "GCF_026782725"
  - "GCF_026782705"
  - "GCF_000522885"
  - "GCF_000522705"
  - "GCF_021013185"
  - "GCF_000522825"
  - "GCF_000522845"
  - "GCF_901875565"
  - "GCF_029071925"
  - "GCF_024762195"
  - "GCF_024762175"
  - "GCF_028325405"
  - "GCF_015670285"
  - "GCF_015669655"
  - "GCF_000375505"
  - "GCF_018619415"
  - "GCF_019048645"
  - "GCF_002083175"
  - "GCF_012273155"
  - "GCF_000339815"
  - "GCF_000271865"
  - "GCF_002157665"
  - "GCF_002155285"
  - "GCF_000347835"
  - "GCF_020531125"
  - "GCF_020529965"
  - "GCF_020529995"
  - "GCF_020529445"
  - "GCF_020529385"
  - "GCF_020529945"
  - "GCF_020529915"
  - "GCF_020529705"
  - "GCF_020529405"
  - "GCF_020529255"
  - "GCF_020529325"
  - "GCF_020529305"
  - "GCF_020529685"
  - "GCF_020530845"
  - "GCF_020531625"
  - "GCF_020529225"
  - "GCF_020529245"
  - "GCF_020531665"
  - "GCF_020530685"
  - "GCF_020530645"
  - "GCF_020531085"
  - "GCF_020531635"
  - "GCF_020531605"
  - "GCF_020531585"
  - "GCF_020531565"
  - "GCF_020530585"
  - "GCF_020530665"
  - "GCF_020530545"
  - "GCF_020530565"
  - "GCF_020530605"
  - "GCF_020531325"
  - "GCF_020530905"
  - "GCF_020530865"
  - "GCF_020530795"
  - "GCF_020530785"
  - "GCF_020531485"
  - "GCF_020531505"
  - "GCF_020530805"
  - "GCF_020531545"
  - "GCF_020531305"
  - "GCF_020531465"
  - "GCF_020529795"
  - "GCF_020530525"
  - "GCF_020531445"
  - "GCF_020531525"
  - "GCF_020531205"
  - "GCF_020530925"
  - "GCF_020529565"
  - "GCF_020529765"
  - "GCF_020530465"
  - "GCF_020530875"
  - "GCF_020529845"
  - "GCF_020529825"
  - "GCF_020531225"
  - "GCF_020529525"
  - "GCF_020529785"
  - "GCF_020529725"
  - "GCF_020530445"
  - "GCF_020529485"
  - "GCF_020530745"
  - "GCF_020530495"
  - "GCF_020531245"
  - "GCF_020530485"
  - "GCF_020529885"
  - "GCF_020529665"
  - "GCF_020529745"
  - "GCF_020529465"
  - "GCF_020531285"
  - "GCF_020529495"
  - "GCF_020529865"
  - "GCF_020529595"
  - "GCF_020530725"
  - "GCF_020529905"
  - "GCF_020530705"
  - "GCF_020530985"
  - "GCF_020530765"
  - "GCF_020529645"
  - "GCF_020529585"
  - "GCF_020529625"
  - "GCF_020529545"
  - "GCF_020531425"
  - "GCF_020531405"
  - "GCF_020531165"
  - "GCF_020530965"
  - "GCF_020531185"
  - "GCF_020531105"
  - "GCF_020531145"
  - "GCF_020531355"
  - "GCF_020531065"
  - "GCF_020530945"
  - "GCF_020531005"
  - "GCF_020530125"
  - "GCF_020531045"
  - "GCF_020531025"
  - "GCF_020530165"
  - "GCF_020530075"
  - "GCF_020530245"
  - "GCF_020530185"
  - "GCF_020530145"
  - "GCF_020531345"
  - "GCF_020530625"
  - "GCF_020529275"
  - "GCF_020530425"
  - "GCF_020530105"
  - "GCF_020530025"
  - "GCF_020530065"
  - "GCF_020530305"
  - "GCF_020530045"
  - "GCF_020530345"
  - "GCF_020531385"
  - "GCF_020530355"
  - "GCF_020530285"
  - "GCF_020529345"
  - "GCF_020530405"
  - "GCF_020531255"
  - "GCF_020530365"
  - "GCF_020529365"
  - "GCF_020530225"
  - "GCF_020530325"
  - "GCF_020530255"
  - "GCF_020530205"
  - "GCF_020529985"
  - "GCF_020529415"
  - "GCF_003691695"
  - "GCF_002995555"
  - "GCF_000284575"
  - "GCF_000339835"
  - "GCF_000339135"
  - "GCF_000339935"
  - "GCF_008831325"
  - "GCF_902365065"
  - "GCF_000339335"
  - "GCF_000339955"
  - "GCF_000339855"
  - "GCF_000339975"
  - "GCF_006739205"
  - "GCF_009738105"
  - "GCF_900475095"
  - "GCF_900636835"
  - "GCF_900459345"
  - "GCF_000339395"
  - "GCF_000339295"
  - "GCF_001558215"
  - "GCF_000340075"
  - "GCF_000339875"
  - "GCF_000339895"
  - "GCF_000339495"
  - "GCF_000339915"
  - "GCF_000339355"
  - "GCF_000091645"
  - "GCF_000339415"
  - "GCF_000339755"
  - "GCF_000339635"
  - "GCF_011765545"
  - "GCF_011765525"
  - "GCF_002213065"
  - "GCF_002213035"
  - "GCF_002212965"
  - "GCF_002212855"
  - "GCF_002213005"
  - "GCF_002212885"
  - "GCF_002212905"
  - "GCF_002212845"
  - "GCF_002212995"
  - "GCF_002212925"
  - "GCF_002212935"
  - "GCF_000496535"
  - "GCF_000496555"
  - "GCF_000339115"
  - "GCF_028326035"
  - "GCF_011765505"
  - "GCF_000339055"
  - "GCF_023109585"
  - "GCF_011765485"
  - "GCF_000339615"
  - "GCF_000339075"
  - "GCF_000340015"
  - "GCF_000339095"
  - "GCF_000339435"
  - "GCF_000339575"
  - "GCF_000340135"
  - "GCF_000339455"
  - "GCF_003172975"
  - "GCF_000340035"
  - "GCF_000340055"
  - "GCF_000339375"
  - "GCF_008831345"
  - "GCF_000228745"
  - "GCF_000228765"
  - "GCF_000228785"
  - "GCF_000228805"
  - "GCF_000228825"
  - "GCF_000228845"
  - "GCF_000228865"
  - "GCF_000228885"
  - "GCF_000228905"
  - "GCF_000228925"
  - "GCF_000228945"
  - "GCF_000228965"
  - "GCF_000228985"
  - "GCF_000229005"
  - "GCF_000229025"
  - "GCF_000229045"
  - "GCF_000229065"
  - "GCF_000229085"
  - "GCF_000229105"
  - "GCF_000229125"
  - "GCF_000229145"
  - "GCF_000229165"
  - "GCF_000229185"
  - "GCF_000229205"
  - "GCF_000229225"
  - "GCF_000229245"
  - "GCF_000229265"
  - "GCF_000229285"
  - "GCF_000229305"
  - "GCF_000229325"
  - "GCF_000229345"
  - "GCF_000229365"
  - "GCF_000229385"
  - "GCF_000229405"
  - "GCF_000229425"
  - "GCF_000229445"
  - "GCF_000229465"
  - "GCF_000229485"
  - "GCF_000229505"
  - "GCF_000229525"
  - "GCF_000229545"
  - "GCF_000229565"
  - "GCF_000229585"
  - "GCF_000229605"
  - "GCF_000229625"
  - "GCF_000229645"
  - "GCF_000229665"
  - "GCF_000229685"
  - "GCF_000229705"
  - "GCF_000229725"
  - "GCF_000229745"
  - "GCF_000229765"
  - "GCF_000229785"
  - "GCF_000229805"
  - "GCF_000229825"
  - "GCF_000229845"
  - "GCF_000229865"
  - "GCF_000229885"
  - "GCF_000229905"
  - "GCF_000229925"
  - "GCF_000229945"
  - "GCF_000229965"
  - "GCF_000229985"
  - "GCF_000230005"
  - "GCF_000230025"
  - "GCF_000230045"
  - "GCF_000230065"
  - "GCF_000230085"
  - "GCF_000230105"
  - "GCF_000230125"
  - "GCF_000230145"
  - "GCF_000230165"
  - "GCF_000230185"
  - "GCF_000230205"
  - "GCF_000230225"
  - "GCF_000339795"
  - "GCF_000339475"
  - "GCF_000340175"
  - "GCF_024762155"
  - "GCF_008831365"
  - "GCF_012641085"
  - "GCF_000007465"
  - "GCF_000817065"
  - "GCF_012642405"
  - "GCF_012642225"
  - "GCF_012641665"
  - "GCF_012641625"
  - "GCF_012641605"
  - "GCF_012641615"
  - "GCF_012641575"
  - "GCF_012641565"
  - "GCF_012642205"
  - "GCF_012642185"
  - "GCF_012642165"
  - "GCF_012642365"
  - "GCF_012642145"
  - "GCF_012642125"
  - "GCF_012642105"
  - "GCF_012641545"
  - "GCF_012642085"
  - "GCF_012642055"
  - "GCF_012642035"
  - "GCF_012642015"
  - "GCF_012642005"
  - "GCF_012641975"
  - "GCF_012642345"
  - "GCF_012641965"
  - "GCF_012641935"
  - "GCF_012641925"
  - "GCF_012641905"
  - "GCF_012641855"
  - "GCF_012641885"
  - "GCF_012641825"
  - "GCF_012641845"
  - "GCF_012641765"
  - "GCF_012641775"
  - "GCF_012642355"
  - "GCF_012641805"
  - "GCF_012642325"
  - "GCF_012642305"
  - "GCF_012642275"
  - "GCF_012642265"
  - "GCF_012642235"
  - "GCF_000339995"
  - "GCF_026782685"

additional_genomes:
  accession_list:
  - "G09_spades_contigs.fasta"
  - "G18_spades_contigs.fasta"

SRA_download:
  accession_list:


anvio_parameters:
  run_full_anvio: "NO" #If NO, then mashtree will create a tree only. This is advised when you have more than 100 genomes!
  functional_homogeneity_index_threshold: .95 #This will be the starting value; if no gene clusters are found, it will incrementally increase by 0.01 until some are found or it reaches 1.0.
  annotate_trnas: "NO"
  annotate_ncbi_cogs: "NO"
  annotate_kegg_kofams: "NO"
  annotate_scg_taxonomy: "NO"