# YAML 
## Outgroup: GCF_025311495.1

project:
  name: "002"

reference_genomes:
  accession_list:
  - "GCF_025311495.1"
  - "GCF_029961225.1"
  - "GCF_000966835.2"
  - "GCF_001077025.1"
  - "GCF_001368755.1"
  - "GCF_001436835.1"
  - "GCF_001742205.1"
  - "GCF_001854105.1"
  - "GCF_001941785.1"
  - "GCF_001982185.1"
  - "GCF_002119645.1"
  - "GCF_002192435.1"
  - "GCF_002204495.1"
  - "GCF_002242615.1"
  - "GCF_002591935.1"
  - "GCF_002794275.1"
  - "GCF_002794315.1"
  - "GCF_002794375.1"
  - "GCF_002798075.1"
  - "GCF_002863265.1"
  - "GCF_002869825.2"
  - "GCF_002899655.1"
  - "GCF_003053105.1"
  - "GCF_003061865.1"
  - "GCF_003255875.1"
  - "GCF_003261135.1"
  - "GCF_003346315.1"
  - "GCF_003346325.1"
  - "GCF_003346795.1"
  - "GCF_003462755.1"
  - "GCF_003464285.1"
  - "GCF_003855655.1"
  - "GCF_003860425.1"
  - "GCF_004063515.1"
  - "GCF_004063635.1"
  - "GCF_004208815.1"
  - "GCF_004683795.1"
  - "GCF_004683835.1"
  - "GCF_005341425.1"
  - "GCF_005864145.1"
  - "GCF_006538825.1"
  - "GCF_008802915.1"
  - "GCF_008868475.1"
  - "GCF_009295755.1"
  - "GCF_009362835.1"
  - "GCF_009676625.1"
  - "GCF_009914845.1"
  - "GCF_011032745.1"
  - "GCF_011032765.1"
  - "GCF_011290755.1"
  - "GCF_011420355.1"
  - "GCF_012070605.1"
  - "GCF_012070625.1"
  - "GCF_012273035.1"
  - "GCF_013394085.1"
  - "GCF_014830195.1"
  - "GCF_014926345.1"
  - "GCF_015160755.1"
  - "GCF_016617695.1"
  - "GCF_016861465.1"
  - "GCF_016861955.1"
  - "GCF_016918895.1"
  - "GCF_017068315.1"
  - "GCF_017134335.1"
  - "GCF_017134355.1"
  - "GCF_017134375.1"
  - "GCF_018398375.1"
  - "GCF_018732245.1"
  - "GCF_018866265.1"
  - "GCF_018884205.1"
  - "GCF_019890875.1"
  - "GCF_020520555.1"
  - "GCF_020844625.1"
  - "GCF_021128975.1"
  - "GCF_021278125.1"
  - "GCF_021582915.1"
  - "GCF_022509325.1"
  - "GCF_022509335.1"
  - "GCF_022509365.1"
  - "GCF_022509385.1"
  - "GCF_022509425.1"
  - "GCF_022509445.1"
  - "GCF_022509455.1"
  - "GCF_022819245.1"
  - "GCF_022844685.1"
  - "GCF_023370755.1"
  - "GCF_023612195.1"
  - "GCF_024054255.2"
  - "GCF_024137685.1"
  - "GCF_024204625.1"
  - "GCF_024385625.1"
  - "GCF_024494505.1"
  - "GCF_024637935.1"
  - "GCF_024665195.1"
  - "GCF_024800585.1"
  - "GCF_025122475.1"
  - "GCF_025122575.1"
  - "GCF_025185825.1"
  - "GCF_025185835.1"
  - "GCF_025185985.1"
  - "GCF_025186015.1"
  - "GCF_025191505.1"
  - "GCF_025191545.1"
  - "GCF_025191565.1"
  - "GCF_025191585.1"
  - "GCF_025191625.1"
  - "GCF_025191635.1"
  - "GCF_025191645.1"
  - "GCF_025191705.1"
  - "GCF_025191725.1"
  - "GCF_025191745.1"
  - "GCF_025191755.1"
  - "GCF_025191785.1"
  - "GCF_025191805.1"
  - "GCF_025191825.1"
  - "GCF_025211175.1"
  - "GCF_025780195.1"
  - "GCF_025809275.1"
  - "GCF_026184215.1"
  - "GCF_026930525.1"
  - "GCF_027661185.1"
  - "GCF_027668665.1"
  - "GCF_027681055.1"
  - "GCF_027681185.1"
  - "GCF_027681265.1"
  - "GCF_027686025.1"
  - "GCF_027696965.1"
  - "GCF_027857595.1"
  - "GCF_027857625.1"
  - "GCF_028216035.1"
  - "GCF_028462585.1"
  - "GCF_028462685.1"
  - "GCF_028463945.1"
  - "GCF_028743095.1"
  - "GCF_029011825.1"
  - "GCF_029223925.1"
  - "GCF_029223965.1"
  - "GCF_029334835.1"
  - "GCF_029334875.1"
  - "GCF_029537335.1"
  - "GCF_029606345.1"
  - "GCF_029691425.1"
  - "GCF_029823225.1"
  - "GCF_029872335.1"
  - "GCF_030218985.1"
  - "GCF_030290995.1"
  - "GCF_030291755.1"
  - "GCF_030665445.1"
  - "GCF_030770375.1"
  - "GCF_030845215.1"
  - "GCF_030851245.1"
  - "GCF_030939205.1"
  - "GCF_030939465.1"
  - "GCF_030939605.1"
  - "GCF_030939615.1"
  - "GCF_030971345.1"
  - "GCF_030971365.1"
  - "GCF_031460995.1"
  - "GCF_032598825.1"
  - "GCF_032598845.1"
  - "GCF_034048795.1"
  - "GCF_034328545.1"
  - "GCF_035609185.1"
  - "GCF_035621415.1"
  - "GCF_036431245.1"
  - "GCF_036431305.1"
  - "GCF_036431325.1"
  - "GCF_036431365.1"
  - "GCF_036431385.1"
  - "GCF_036431405.1"
  - "GCF_036431425.1"
  - "GCF_036431445.1"
  - "GCF_036431465.1"
  - "GCF_036431485.1"
  - "GCF_036431505.1"
  - "GCF_036784755.1"
  - "GCF_037006085.1"
  - "GCF_037164145.1"
  - "GCF_037168225.1"
  - "GCF_037407275.1"
  - "GCF_037966785.1"
  - "GCF_038739575.1"
  - "GCF_039566235.1"
  - "GCF_039566575.1"
  - "GCF_039566785.1"
  - "GCF_039566885.1"
  - "GCF_039944225.1"
  - "GCF_040235315.1"
  - "GCF_040267735.1"
  - "GCF_040347825.1"
  - "GCF_040347895.1"
  - "GCF_040505795.1"
  - "GCF_040785075.1"
  - "GCF_040790835.1"
  - "GCF_041200135.1"
  - "GCF_041380155.1"
  - "GCF_041413225.1"
  - "GCF_041464195.1"
  - "GCF_043950145.1"
  - "GCF_044341635.1"
  - "GCF_045272275.1"
  - "GCF_045527665.1"
  - "GCF_045527705.1"
  - "GCF_045786175.1"
  - "GCF_045809205.1"
  - "GCF_046064525.1"
  - "GCF_046603855.1"
  - "GCF_046603985.1"
  - "GCF_048833695.1"
  - "GCF_049070625.1"
  - "GCF_049180395.1"
  - "GCF_049180415.1"
  - "GCF_049180435.1"
  - "GCF_049180455.1"
  - "GCF_049180475.1"
  - "GCF_049180495.1"
  - "GCF_049180515.1"
  - "GCF_049532745.1"
  - "GCF_050032855.1"
  - "GCF_050847325.1"
  - "GCF_051045955.1"
  - "GCF_051094845.1"
  - "GCF_051094935.1"
  - "GCF_051095625.1"
  - "GCF_051152655.1"
  - "GCF_051152675.1"
  - "GCF_051152755.1"
  - "GCF_051152775.1"
  - "GCF_051152795.1"
  - "GCF_051152875.1"
  - "GCF_051152895.1"
  - "GCF_051152915.1"
  - "GCF_051153095.1"
  - "GCF_051153515.1"
  - "GCF_051153535.1"
  - "GCF_051153595.1"
  - "GCF_051153615.1"
  - "GCF_051153655.1"
  - "GCF_051153715.1"
  - "GCF_051153835.1"
  - "GCF_051153895.1"
  - "GCF_051153955.1"
  - "GCF_051153965.1"
  - "GCF_051154915.1"
  - "GCF_051154955.1"
  - "GCF_051154975.1"
  - "GCF_051155035.1"
  - "GCF_051155315.1"
  - "GCF_051155375.1"
  - "GCF_051155415.1"
  - "GCF_051155435.1"
  - "GCF_051155455.1"
  - "GCF_051156615.1"
  - "GCF_051156715.1"
  - "GCF_051156735.1"
  - "GCF_051156755.1"
  - "GCF_051156775.1"
  - "GCF_051156915.1"
  - "GCF_051156935.1"
  - "GCF_051156955.1"
  - "GCF_051156975.1"
  - "GCF_051156995.1"
  - "GCF_051157015.1"
  - "GCF_051157035.1"
  - "GCF_051157055.1"
  - "GCF_051157095.1"
  - "GCF_051157155.1"
  - "GCF_051157215.1"
  - "GCF_051157235.1"
  - "GCF_051157245.1"
  - "GCF_051157495.1"
  - "GCF_051157695.1"
  - "GCF_051157755.1"
  - "GCF_051157795.1"
  - "GCF_051158035.1"
  - "GCF_051158055.1"
  - "GCF_051158135.1"
  - "GCF_051158295.1"
  - "GCF_051158395.1"
  - "GCF_051158415.1"
  - "GCF_051158915.1"
  - "GCF_051158935.1"
  - "GCF_051628875.1"
  - "GCF_051752105.1"
  - "GCF_051949185.1"
  - "GCF_052029635.1"
  - "GCF_052084705.1"
  - "GCF_052221125.1"
  - "GCF_052784075.1"
  - "GCF_052881015.1"
  - "GCF_053049375.1"
  - "GCF_053471025.1"
  - "GCF_053471045.1"
  - "GCF_053471065.1"
  - "GCF_053471085.1"
  - "GCF_053471105.1"
  - "GCF_053471125.1"
  - "GCF_053471145.1"
  - "GCF_053471705.1"
  - "GCF_053543435.1"
  - "GCF_900163585.1"
  - "GCF_900163595.1"
  - "GCF_900205745.1"
  - "GCF_900290185.1"
  - "GCF_902363965.1"
  - "GCF_925284415.1"
  - "GCF_945190155.1"
  - "GCF_945190275.1"
  - "GCF_963237045.1"
  - "GCF_964210865.1"
  - "GCF_000162395.1"
  - "GCF_000466785.3"
  - "GCF_000159215.1"
  - "GCF_014488995.1"
  - "GCF_000397165.1"
  - "GCF_000417005.1"
  - "GCF_000010145.1"
  - "GCF_001039735.1"
  - "GCF_000472265.1"
  - "GCF_000496435.1"

SRA_download:
  accession_list:
    - "ERR570130"
    - "ERR570149"
    - "ERR570161"
    - "ERR570194"
    - "ERR570222"
    
anvio_parameters:
  run_full_anvio: "NO" #If NO, then mashtree will create a tree only. This is advised when you have more than 100 genomes!
  functional_homogeneity_index_threshold: .95 #This will be the starting value; if no gene clusters are found, it will incrementally increase by 0.01 until some are found or it reaches 1.0.
  annotate_trnas: "NO"
  annotate_ncbi_cogs: "NO"
  annotate_kegg_kofams: "NO"
  annotate_scg_taxonomy: "NO"